//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Cuentas_por_cobrar
    {
        public int DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CardCode { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> DiasTranscurridos { get; set; }
        public Nullable<int> Dif { get; set; }
        public Nullable<short> GroupNum { get; set; }
        public Nullable<short> ExtraDays { get; set; }
        public Nullable<int> Antiguedad { get; set; }
    }
}
