//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Dim_Empleados
    {
        public int Id_Vendedor { get; set; }
        public string Vendedor { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public string Activo { get; set; }
        public string Tipo_Empleado { get; set; }
        public string Comision_Especial { get; set; }
    }
}
