//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Dim_Productos
    {
        public string Id_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public string Codigo_Barras { get; set; }
        public Nullable<short> Id_Grupo_Productos { get; set; }
        public string Grupo_Productos { get; set; }
        public Nullable<decimal> Inventario { get; set; }
        public string Id_Proveedor { get; set; }
        public string Proveedor { get; set; }
        public string Imagen { get; set; }
        public string Ruta_Imagen { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Id_Linea { get; set; }
        public string Linea { get; set; }
        public string Codigo_Anterior { get; set; }
        public string Codigo_Producto_Proveedor { get; set; }
        public string Id_Marca { get; set; }
        public string Marca { get; set; }
        public string Activo { get; set; }
    }
}
