//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Dim_Customers
    {
        public string Id_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public Nullable<short> Id_Grupo_Clientes { get; set; }
        public string Grupo_Clientes { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public Nullable<short> Id_Termino_Pago { get; set; }
        public string Termino_Pago { get; set; }
        public Nullable<decimal> Limite_Credito { get; set; }
        public decimal Saldo { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string DUI { get; set; }
        public string NIT { get; set; }
        public string NRC { get; set; }
        public string Id_Tipo_Contribuyente { get; set; }
        public string Tipo_Contribuyente { get; set; }
        public string Activo { get; set; }
    }
}
