//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Facturas_Encabezado
    {
        public int DocEntry { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> NoDoc { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Id_Serie { get; set; }
        public string Serie { get; set; }
        public string Id_Cliente { get; set; }
        public Nullable<decimal> Total_Sin_Imp { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Percepcion { get; set; }
        public Nullable<decimal> Total_Doc { get; set; }
        public decimal Total_Pagado { get; set; }
        public Nullable<decimal> Pendiente_Pago { get; set; }
        public string Tipo_Doc { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
        public string Cancelado { get; set; }
        public string Id_Sucursal { get; set; }
        public string Sucursal { get; set; }
        public string Id_TipoDoc_Interno { get; set; }
        public string TipoDoc_Interno { get; set; }
        public string Cliente { get; set; }
        public Nullable<short> Hora_Fac { get; set; }
    }
}
