//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Facturas_Detalle
    {
        public Nullable<int> DocEntry { get; set; }
        public string Id_Producto { get; set; }
        public Nullable<decimal> Unidades { get; set; }
        public decimal UdM_Compra { get; set; }
        public Nullable<decimal> Unidades_Venta { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public Nullable<decimal> Total_Ganancia { get; set; }
        public Nullable<decimal> Total_Costo { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public Nullable<decimal> Descuento_Porcentaje { get; set; }
        public Nullable<decimal> Precio_Sin_Desc { get; set; }
    }
}
