//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Facturas_Encabezado
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string DocStatus { get; set; }
        public string ID_sucursal { get; set; }
        public string tipoDocumento { get; set; }
        public Nullable<short> dochour { get; set; }
        public string Sucursal { get; set; }
    }
}
