//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Koncept_dbEntities : DbContext
    {
        public Koncept_dbEntities()
            : base("name=Koncept_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<Tb_newCustomers> Tb_newCustomers { get; set; }
        public virtual DbSet<Tb_Invoices> Tb_Invoices { get; set; }
        public virtual DbSet<Tb_Invoices_Details> Tb_Invoices_Details { get; set; }
    }
}
