//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        public int ID_User { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string Departments { get; set; }
        public string Roles { get; set; }
        public bool Active { get; set; }
        public System.DateTime Creation_date { get; set; }
        public string ID_SalesPoint { get; set; }
        public string Assigned_SalesPoint { get; set; }
        public Nullable<int> ID_SalesRep { get; set; }
    }
}
