//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Invoices_Anticipos
    {
        public int ID_detail { get; set; }
        public int Docnum { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cod_tipoPago { get; set; }
        public string TipoPago { get; set; }
        public decimal Anticipo { get; set; }
        public decimal TotalCancelado { get; set; }
        public decimal SaldoPendiente { get; set; }
        public string BancoCheque { get; set; }
        public string NumeroCheque { get; set; }
        public string TitularTarjeta { get; set; }
        public string DocumentoTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string VoucherTarjeta { get; set; }
        public string Docentry { get; set; }
        public string MensajeError { get; set; }
        public int Error { get; set; }
        public int Estado { get; set; }
    }
}
