//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncepto_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_newCustomers
    {
        public int ID_customer { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Departamento { get; set; }
        public int Tipo_contribuyente { get; set; }
        public string DUI { get; set; }
        public string NRC { get; set; }
        public string NIT { get; set; }
        public string Contribuyente { get; set; }
        public string ID_SAP { get; set; }
        public System.DateTime Creation_date { get; set; }
        public int ID_grupoCliente { get; set; }
        public string GrupoCliente { get; set; }
        public int ID_vendedor { get; set; }
        public string ID_Sucursal { get; set; }
    }
}
